# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acCtr <- function(exdata, centroids, i) {
    .Call('_Kmeansimp_acCtr', PACKAGE = 'Kmeansimp', exdata, centroids, i)
}

doClus <- function(dataset, centroids) {
    .Call('_Kmeansimp_doClus', PACKAGE = 'Kmeansimp', dataset, centroids)
}

